/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.usfirst.frc2877.RoadKill.commands;

import org.usfirst.frc2877.RoadKill.Robot;
public class CANDrive {
        public CANDrive() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
        requires(Robot.cANDriveTrain);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        double x = Robot.oi.joystick1.getX();
        double y = Robot.oi.joystick1.getY();
        Robot.cANDriveTrain.drive(x, y);
 //       double whiteWheel = -0.40;
 //       double blackWheel = -0.70;
 //       Robot.driveTrain.drive(whiteWheel, blackWheel);

    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return Robot.cANDriveTrain.limitSwitch.get();
    }
    // Called once after isFinished returns true
    protected void end() {
        Robot.cANDriveTrain.drive(0, 0);
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}

